### ISSUE TITLE
使用台开启tunneld失败

### ISSUE THREAD

**Issue by Giteers** [codeskyblue/tidevice3#20]
INFO:     Started server process [49138]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/asyncio/client.py", line 95, in connect
    protocol.connect(addr)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/asyncio/protocol.py", line 60, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/quic/connection.py", line 504, in connect
    self._connect(now=now)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/quic/connection.py", line 1217, in _connect
    self._initialize(self._peer_cid.cid)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/quic/connection.py", line 1373, in _initialize
    raise RuntimeError(
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/pymobiledevice3", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/__main__.py", line 98, in main
    cli()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/cli/cli_common.py", line 146, in wrapper
    func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/cli/remote.py", line 197, in cli_start_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout, protocol=protocol),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/cli/remote.py", line 112, in tunnel_task
    async with start_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymobiledevice3/remote/core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/asyncio/client.py", line 100, in connect
    protocol.close()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/asyncio/protocol.py", line 52, in close
    self.transmit()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/asyncio/protocol.py", line 102, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/qh3/quic/connection.py", line 541, in datagrams_to_send
    crypto = self._cryptos[epoch]
KeyError: <Epoch.INITIAL: 0>
udid: 00008120-000E3D680CF1A01E start-tunnel failed
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice3/cli/tunneld.py", line 116, in _start_tunnel_keeper
    addr, process = start_tunnel(self.pmd3_path, udid)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice3/utils/common.py", line 28, in wrapper
    return fn(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tidevice3/cli/tunneld.py", line 74, in start_tunnel
    raise TunnelError("pmd3 start-tunnel empty response")
tidevice3.cli.tunneld.TunnelError: pmd3 start-tunnel empty response
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [49138]

**Comment by dusk0504** [comment]
我也遇到相同的问题，求大佬解答

**Comment by codeskyblue** [comment]
感觉可以给qh3降一下版本
