### ISSUE TITLE
t3 fsync 的所有命令一直报 pymobiledevice3.exceptions.PyMobileDevice3Exception: InstallationLookupFailed

### ISSUE THREAD

**Issue by ZSCharlie** [codeskyblue/tidevice3#26]
应用在手机上确定是存在的，用t3 app list列出来能看到。
例如com.netease.onmyoji
运行 t3 fsync -B com.netease.onmyoji ls /Documents 命令就会出现pymobiledevice3.exceptions.PyMobileDevice3Exception: InstallationLookupFailed
使用ls rm push pull都会报错

**Comment by ZSCharlie** [comment]
iOS版本17.5.1

**Comment by lxlzzz901211** [comment]
> 应用在手机上确定是存在的，用t3 app list列出来能看到。 例如com.netease.onmyoji 运行 t3 fsync -B com.netease.onmyoji ls /Documents 命令就会出现pymobiledevice3.exceptions.PyMobileDevice3Exception: InstallationLookupFailed 使用ls rm push pull都会报错

我也遇到了这样的问题，也是fsync遇到的，IOS17.3，Macbookpro

```
unhandled exception: InstallationLookupFailed
Traceback (most recent call last):
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/tidevice3/__main__.py", line 20, in main
    cli(auto_envvar_prefix='T3')
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/tidevice3/cli/cli_common.py", line 44, in new_func
    return ctx.invoke(func, service_provider, *args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/tidevice3/cli/fsync.py", line 31, in new_func
    afc = HouseArrestService(lockdown=service_provider,
                             bundle_id=ctx.obj['bundle_id'],
                             documents_only=ctx.obj["documents"])
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/pymobiledevice3/services/house_arrest.py", line 27, in __init__
    self.send_command(bundle_id, cmd)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/Users/liuxin/.local/pipx/venvs/tidevice3/lib/python3.13/site-packages/pymobiledevice3/services/house_arrest.py", line 39, in send_command
    raise PyMobileDevice3Exception(error)
pymobiledevice3.exceptions.PyMobileDevice3Exception: InstallationLookupFailed
```
