### ISSUE TITLE
tidevice3支持windows么？

### ISSUE THREAD

**Issue by wangyuqi2017** [codeskyblue/tidevice3#6]

**Comment by codeskyblue** [comment]
昨天刚改了一下，你试试，估计可以

**Comment by katrinaaaaaaa** [comment]
![xiezuo20240326-160123](https://github.com/codeskyblue/tidevice3/assets/45142768/4df9f115-124c-46a1-8d5d-5d0819472018)

**Comment by Jim-JimZ** [comment]
作者大大，打扰了，我想问下windows运行，起了tunneld后在connect_remote_service_discovery_service方法里的resp = requests.get(tunneld_url, `timeout=DEFAULT_TIMEOUT)会以下报错，有啥解决方法吗，我试过换了端口没效，电脑似乎也没报什么防火墙错误。

```
起个tunneld的服务
2024-04-23 15:37:57.630 | INFO     | src.remote_api.feishuapi:__init__:45 - 使用从json文件中读取的飞书参数
2024-04-23 15:37:57 DESKTOP-HSJ49RH tidevice3.cli.tunneld[11664] INFO [00008030-********232802E] cmd: pymobiledevice3 remote start-tunnel --script-mode --udid 00008030-********232802E
调试output_str： fd85:9aa:89f9::1 57691
截图
2024-04-23 15:38:03 DESKTOP-HSJ49RH pymobiledevice3.cli.remote[3792] INFO tunnel created
2024-04-23 15:38:03 DESKTOP-HSJ49RH tidevice3.cli.tunneld[11664] INFO [00008030-********232802E] tunnel address: ['fd85:9aa:89f9::1', 57691]
调试lockdown： <PlistUsbmuxLockdownClient ID:00008030-********232802E VERSION:17.4.1 TYPE:iPhone12,1 PAIRED:True>
调试：判断为iOS17,进行service连接
调试开始:
Traceback (most recent call last):
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\connection.py", line 198, in _new_conn
    sock = connection.create_connection(
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\connection.py", line 400, in request
    self.endheaders()
  File "E:\anaconda\envs\fwtest\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "E:\anaconda\envs\fwtest\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "E:\anaconda\envs\fwtest\lib\http\client.py", line 976, in send
    self.connect()
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\connection.py", line 238, in connect
    self.sock = self._new_conn()
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001AB2A59BDC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\anaconda\envs\fwtest\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\anaconda\envs\fwtest\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8120): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AB2A59BDC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda\envs\fwtest\lib\site-packages\tidevice3\api.py", line 86, in connect_remote_service_discovery_service
    resp = requests.get(tunneld_url, timeout=DEFAULT_TIMEOUT)
  File "E:\anaconda\envs\fwtest\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "E:\anaconda\envs\fwtest\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\anaconda\envs\fwtest\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\anaconda\envs\fwtest\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\anaconda\envs\fwtest\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8120): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001AB2A59BDC0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
```
![img_v3_02a7_ee83eb80-aef4-4ea1-ba7a-df2d84711d2g](https://github.com/codeskyblue/tidevice3/assets/83862970/fe4823cd-a620-4658-b4ee-94da673cfa9a)
