### ISSUE TITLE
Error: ('tunneld not ready for device', '00008101-001A74391A11A01E')

### ISSUE THREAD

**Issue by katrinaaaaaaa** [codeskyblue/tidevice3#9]

**Comment by hcx1002** [comment]
我也是这个问题：
`PS C:\WINDOWS\system32> t3 tunneld
INFO:     Started server process [12044]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to quit)
2024-04-12 09:16:45 DESKTOP-RKD4RH6 tidevice3.cli.tunneld[12044] INFO [00008020-000A70800269002E] cmd: C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Scripts\pymobiledevice3.EXE remote start-tunnel --script-mode --udid 00008020-000A70800269002E
Exception in thread 00008020-000A70800269002E keeper:
Traceback (most recent call last):
  File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice3\cli\tunneld.py", line 116, in _start_tunnel_keeper
    addr, process = start_tunnel(self.pmd3_path, udid)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice3\utils\common.py", line 28, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice3\cli\tunneld.py", line 69, in start_tunnel
    process = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
INFO:     127.0.0.1:60957 - "GET / HTTP/1.1" 200 OK
INFO:     127.0.0.1:61874 - "GET / HTTP/1.1" 200 OK`
打开APP
`PS C:\WINDOWS\system32> t3 app launch "vip.test.WebDriverAgentRunner"
Error: ('tunneld not ready for device', '00008020-000A70800269002E')`

怎么通过window启动这个WebDriverAgent呢，WebDriverAgent已经打包安装了，可以直接点启动。但是不稳定，运行几个小时后就闪退了吧，所以需要程序去打开这个WebDriverAgent

**Comment by codeskyblue** [comment]
这个t3 tunneld其实就是封装一下 pmd3的start-tunnel，我也不太清楚为什么明明有pymobiledevice3这个文件，但是运行的时候又提示找不到。你可以直接用  `python3 -m pymobiledevice3 remote tunneld` 试试

**Comment by katrinaaaaaaa** [comment]
> 我也是这个问题：
> 
> ```
> PS C:\WINDOWS\system32> t3 tunneld
> INFO:     Started server process [12044]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://0.0.0.0:5555 (Press CTRL+C to quit)
> 2024-04-12 09:16:45 DESKTOP-RKD4RH6 tidevice3.cli.tunneld[12044] INFO [00008020-000A70800269002E] cmd: C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Scripts\pymobiledevice3.EXE remote start-tunnel --script-mode --udid 00008020-000A70800269002E
> Exception in thread 00008020-000A70800269002E keeper:
> Traceback (most recent call last):
>   File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
>     self.run()
>   File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
>     self._target(*self._args, **self._kwargs)
>   File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice3\cli\tunneld.py", line 116, in _start_tunnel_keeper
>     addr, process = start_tunnel(self.pmd3_path, udid)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice3\utils\common.py", line 28, in wrapper
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\site-packages\tidevice3\cli\tunneld.py", line 69, in start_tunnel
>     process = subprocess.Popen(
>               ^^^^^^^^^^^^^^^^^
>   File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "C:\Users\Yardi\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
>     hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> INFO:     127.0.0.1:60957 - "GET / HTTP/1.1" 200 OK
> INFO:     127.0.0.1:61874 - "GET / HTTP/1.1" 200 OK`
> 打开APP
> PS C:\WINDOWS\system32> t3 app launch "vip.test.WebDriverAgentRunner"
> Error: ('tunneld not ready for device', '00008020-000A70800269002E')`
> ```
> 
> IOS17.4 Xcode15打包 测试 在Mac上可以用上面的命令启动WebDriverAgent，在window上报上面的错误 怎么通过window启动这个WebDriverAgent呢，WebDriverAgent已经打包安装了，可以直接点启动。但是不稳定，运行几个小时后就闪退了吧，所以需要程序去打开这个WebDriverAgent

我也是一样得问题

**Comment by katrinaaaaaaa** [comment]
> 这个t3 tunneld其实就是封装一下 pmd3的start-tunnel，我也不太清楚为什么明明有pymobiledevice3这个文件，但是运行的时候又提示找不到。你可以直接用 `python3 -m pymobiledevice3 remote tunneld` 试试
![image](https://github.com/codeskyblue/tidevice3/assets/45142768/36baf288-d6b7-4edc-8994-791927c3ffa7)
直接用这个吊起后，执行调用应用指令会报这个错误
![image](https://github.com/codeskyblue/tidevice3/assets/45142768/2369addd-97bc-40a1-a056-32778a205f9f)
而执行t3 tunneld又会报这个错误
![image](https://github.com/codeskyblue/tidevice3/assets/45142768/2043ae10-c388-43d5-8cc5-7935c8d7c4f1)

**Comment by katrinaaaaaaa** [comment]
C:\Windows\System32>D:\Python\Python39\Scripts\pymobiledevice3.EXE remote start-tunnel --script-mode --udid 00008101-001A74391A11A01E
D:\Python\Python39\lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
2024-04-19 16:46:37 DESKTOP-JDB2S99 wintun[35036] INFO WetestUsbFilter driver use current version: 11.36.33.666, [11.36.33.666] tested.
2024-04-19 16:46:37 DESKTOP-JDB2S99 wintun[35036] INFO WeTestUsbNcm driver use current version: 11.38.34.492, [11.36.59.886] tested.
2024-04-19 16:46:37 DESKTOP-JDB2S99 wintun[35036] INFO use existing WeTestUsbFilter driver.
2024-04-19 16:46:37 DESKTOP-JDB2S99 wintun[35036] INFO use existing WeTestUsbNcm driver.
Traceback (most recent call last):
  File "D:\Python\Python39\lib\site-packages\qh3\asyncio\client.py", line 95, in connect
    protocol.connect(addr)
  File "D:\Python\Python39\lib\site-packages\qh3\asyncio\protocol.py", line 60, in connect
    self._quic.connect(addr, now=self._loop.time())
  File "D:\Python\Python39\lib\site-packages\qh3\quic\connection.py", line 504, in connect
    self._connect(now=now)
  File "D:\Python\Python39\lib\site-packages\qh3\quic\connection.py", line 1217, in _connect
    self._initialize(self._peer_cid.cid)
  File "D:\Python\Python39\lib\site-packages\qh3\quic\connection.py", line 1373, in _initialize
    raise RuntimeError(
RuntimeError: qh3 v1.0+ no longer support passing cryptography certificate objects within a QuicConfiguration object. Use configuration.load_cert_chain(...) instead using PEM encoded values.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python39\Scripts\pymobiledevice3.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Python\Python39\lib\site-packages\pymobiledevice3\__main__.py", line 98, in main
    cli()
  File "D:\Python\Python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\Python\Python39\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\Python39\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\Python39\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\Python39\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\pymobiledevice3\cli\cli_common.py", line 146, in wrapper
    func(*args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\pymobiledevice3\cli\remote.py", line 197, in cli_start_tunnel
    asyncio.run(tunnel_task(rsd, secrets, script_mode, max_idle_timeout=max_idle_timeout, protocol=protocol),
  File "D:\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "D:\Python\Python39\lib\site-packages\pymobiledevice3\cli\remote.py", line 112, in tunnel_task
    async with start_tunnel(service_provider, secrets=secrets, max_idle_timeout=max_idle_timeout,
  File "D:\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "D:\Python\Python39\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 754, in start_tunnel
    async with service.start_quic_tunnel(
  File "D:\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "D:\Python\Python39\lib\site-packages\pymobiledevice3\remote\core_device_tunnel_service.py", line 376, in start_quic_tunnel
    async with aioquic_connect(
  File "D:\Python\Python39\lib\contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "D:\Python\Python39\lib\site-packages\qh3\asyncio\client.py", line 100, in connect
    protocol.close()
  File "D:\Python\Python39\lib\site-packages\qh3\asyncio\protocol.py", line 52, in close
    self.transmit()
  File "D:\Python\Python39\lib\site-packages\qh3\asyncio\protocol.py", line 102, in transmit
    for data, addr in self._quic.datagrams_to_send(now=self._loop.time()):
  File "D:\Python\Python39\lib\site-packages\qh3\quic\connection.py", line 541, in datagrams_to_send
    crypto = self._cryptos[epoch]
KeyError: <Epoch.INITIAL: 0>
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000027ED7F27AF0>
Traceback (most recent call last):
  File "D:\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "D:\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "D:\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "D:\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
